#!/usr/bin/env bash
# Displays DNS information for specified subdomains

display_subdomain() {
    subdomain=$1
    domain=$2

    record_type=$(dig "$subdomain.$domain" | awk '/ANSWER SECTION:/{getline; print $4}')
    destination=$(dig "$subdomain.$domain" | awk '/ANSWER SECTION:/{getline; print $5}')

    echo "The subdomain $subdomain is a $record_type record and points to $destination"
}

if [ "$#" -eq 1 ]; then
    display_subdomain "www" "$1"
    display_subdomain "lb-01" "$1"
    display_subdomain "web-01" "$1"
    display_subdomain "web-02" "$1"
else
    display_subdomain "$2" "$1"
fi
